### ISSUE TITLE
Wax Blocks missing uncrafting recipes (1.18) [ATM7]

### ISSUE THREAD

**Issue by enigmaquip** [Pdiddy973/AllTheCompressed#14]
Wax can be compressed, but not uncompressed

**Comment by Pdiddy973** [comment]
Fixed in https://github.com/Pdiddy973/AllTheCompressed/commit/435b1558baa7036994e2da2de3a584c26c96bfed

Just need to release + other things for this update

**Comment by brandonvdongen** [comment]
You know.. being the one who found this and for who eniga reported this.. the fact that the typo that made these not work forms the words "Craf wax G" .. is really funny to me..

**Comment by Jadziyah** [comment]
Came here to report this exact issue, so glad it's fixed in upcoming release
