### ISSUE TITLE
[1.18.2] Invalid Recipes?

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pdiddy973/AllTheCompressed#15]
When AllTheCompressed is installed, without ATM or any of its supported modpacks besides vanilla, recipes no longer work; perhaps due to tag changes in Forge. Pictured is the recipe for Oak Planks x1.

AllTheCompressed version: 1.0.3-1.18.2-40.0.12
Forge version: 40.0.19
Minecraft version: 1.18.2

![Untitled](https://user-images.githubusercontent.com/84727791/159136409-278fedd1-bad3-4a0d-8046-da6429f29442.png)

**Comment by Pdiddy973** [comment]
Will look into this in the next few days
