### ISSUE TITLE
[Feature/Suggestion]

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pdiddy973/AllTheCompressed#16]
Even though this mod is made for the ATM modpack, perhaps putting in conditional recipe loading when the requisite mods aren't installed? From what I recall, ATC loads the recipes regardless of whether they have their supported item. If it can't be done conditionally somewhere, perhaps a config option? This mod is currently the 'most complete' Compression-type mod I've found. 

Perhaps a better explanation (and admittedly, the inspiration for my suggestion) can be found here:

https://github.com/Cozary/Issue-Tracker/issues/16

**Comment by Pdiddy973** [comment]
i do have [conditions for recipes](https://github.com/Pdiddy973/AllTheCompressed/blob/1.18/src/main/resources/data/mekanism/recipes/crushing/allthecompressed/cobblestone/1x_to_1x_gravel.json#L11-L25) to make sure mods are loaded? i may of missed on if you can provide a log that shows recipe errors that would be helpful

**Comment by HalcyonSeas73** [comment]
> i do have [conditions for recipes](https://github.com/Pdiddy973/AllTheCompressed/blob/1.18/src/main/resources/data/mekanism/recipes/crushing/allthecompressed/cobblestone/1x_to_1x_gravel.json#L11-L25) to make sure mods are loaded? i may of missed on if you can provide a log that shows recipe errors that would be helpful

Perhaps I'm misunderstanding, as the recipes for (as an example) Platinum show up in JEI, but feature a pink-and-black box. Will do some further testing, as I also have some other (performance) mods installed.

Log: https://paste.ee/p/hZmZq

![Untitled](https://user-images.githubusercontent.com/84727791/159630090-95b950a0-1400-4d70-95a0-381f0de6d02f.png)

**Comment by Pdiddy973** [comment]
OH i get what you mean, just hiding the blocks in JEI not the recipe, i plan on adding that its in the 1.16 version but havent had time to add in 1.18 yet

**Comment by Pdiddy973** [comment]
sorry for the long delay, but update should be soon
