### ISSUE TITLE
[Bug]: Broken Recipes

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pdiddy973/AllTheCompressed#17]
### Minecraft Version

1.18

### Mod Version

1.0.4-1.18.2-40.0.31

### Is Compressium Loaded

Loaded

### What happened?

Compressium recipes do not show in JEI (as expected); however, blocks that Compressium does not support (such as Glass Block 1x) should work. The following recipes cannot be created without JEI:
- Soul Soil
- Glass
- Grass Block
- Hay Block
- Melon Block
- Podzol Block
- Pumpkin Block

In the interest of further testing, I was able to create the following (also Non-Compressium) blocks using their proper recipe, as intended:
-Amethyst
-Blackstone
-Basalt
-Glowstone

Pictured is the (improper) Pumpkin Block recipe, and the (working) Amethyst Block recipe.
![Untitled](https://user-images.githubusercontent.com/84727791/160222060-dded5ba2-a701-4c50-9c06-8bda965a2f82.png)
![Untitled2](https://user-images.githubusercontent.com/84727791/160222088-6bb2255e-6568-437a-9f82-f580b0197ad2.png)

Additionally, despite none of the Log or Plank-type compressed blocks being in Compressium, they also do not load their recipes in JEI.

### latest.log

https://paste.ee/p/2OIeH

**Comment by Pdiddy973** [comment]
planks rfecipes were fixed in 0c8e1e81fe1269c4acfeda189cfa99348549b4fe and released in 1.0.4 today, will look into the other recipes likely tomorrow, thanks for the good report.

**Comment by Pdiddy973** [comment]
i see the issue with the recipes....may release another update tonight deepening on time

**Comment by HalcyonSeas73** [comment]
A full list of the blocks I've been unable to craft (with Compressium loaded), either due to missing or 'blocked'(?) recipes:
- Acacia Log
- Acacia Plank
- Birch Log
- Birch Plank
- Cobbled Deepslate
- Dark Oak Log
- Dark Oak Plank
- Glass
- Grass Block
- Hay Block
- Honey Block
- Jungle Log
- Jungle Plank
- Melon 
- Oak Log
- Oak Plank
- Podzol
- Pumpkin
- Soul Soil
- Spruce Log
- Spruce Plank
- Tuff

**Comment by HalcyonSeas73** [comment]
Interestingly, I just discovered I can craft Oak Plank Block x1, but not further compressions.

**Comment by HalcyonSeas73** [comment]
Mostly fixed!

However, Oak Log and Jungle Planks are now missing their 3x3.
