### ISSUE TITLE
[Feature]: 1.19 Compatibility

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pdiddy973/AllTheCompressed#29]
### Feature Details

Compatibility for 1.19+; [AllTheOres ](https://www.curseforge.com/minecraft/mc-mods/ato)and [AllTheModium](https://www.curseforge.com/minecraft/mc-mods/allthemodium) are already in 1.19.

Compressium has attempted to add custom compressed blocks via .json, but it isn't implemented yet.

**Comment by jeremiahwinsley** [comment]
AllTheCompressed has been released for 1.19.2.
