### ISSUE TITLE
[Feature]: add block tags for the compression levels of blocks

### ISSUE THREAD

**Issue by Minecrafter8001** [Pdiddy973/AllTheCompressed#40]
Have all blocks of levels have a block tag associated with that level, so all 3x blocks would have the tag '#allthecompressed:3x'.
 Just a QOL feature for filters in other mods/packs. 
Not sure if it's even possible or how hard it would be to implement, but I think it's a good idea.

**Comment by Minecrafter8001** [comment]
also add compressed raw blocks please

**Comment by jeremiahwinsley** [comment]
Added in 1.21.
