### ISSUE TITLE
Bug: Spirited Block to Energy expensive

### ISSUE THREAD

**Issue by Ratles-1** [Pdiddy973/AllTheCompressed#53]
https://github.com/Pdiddy973/AllTheCompressed/blob/38551c56f701d0b377be04a4cbf7cb83ceacc736/src/generated/resources/data/allthecompressed/recipe/energizing/spirited_crystal_block/x0.json#L9

A single crystal takes 1MFE to form, a Block should take 9MFE not 81MFE.

**Comment by jeremiahwinsley** [comment]
Fixed in 4.0.1.
