### ISSUE TITLE
Missing Vanilla Blocks/ Suggestions [NOISSUE]

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pdiddy973/AllTheCompressed#6]
- Compressed Diorite/Granite/Andesite/Blackstone/Basalt
- Compressed Grass Block/Podzol/Soul Soil
- Compressed Pumpkin/Melon/Hay Bales/Bamboo

Other compression-type mods add these features, I thought these might be useful.

**Comment by Kurunoa** [comment]
Compressed Deepslate and Compressed Cobbled Deepslate

**Comment by Pdiddy973** [comment]
> * Compressed Diorite/Granite/Andesite/Blackstone/Basalt
> * Compressed Grass Block/Podzol/Soul Soil
> * Compressed Pumpkin/Melon/Hay Bales/Bamboo
> 
> Other compression-type mods add these features, I thought these might be useful.

only one I don't plan on doing rn is bamboo since it does not have a a block variant

**Comment by Pdiddy973** [comment]
added in 1.17 version, will add to 1.16 later.
