### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kurunoa** [Pdiddy973/AllTheCompressed#7]
### Minecraft Version

1.17.1

### Mod Version

0.0.3

### Is Compressium Loaded

Not Loaded

### What happened?

When you place blocks like Cobblestone Block 1x, it cannot be removed. They can be pistoned around but not mined/recovered. This is on the official All The Mods 7 server

### latest.log

no

**Comment by Pdiddy973** [comment]
Fixed in 0.0.4
